import time
import math
time.sleep(0)
math.ceil(1)

print('>'*40)
print('{:^40}'.format('CALCULADORA PARA REVESTIMENTO - MOD. 1'))
print('<'*40)
print('TIPO DE CÁLCULO:')
print('>'*40)
print('''[1]ÁREA TOTAL
[2]INDIVIDUAL
[3]POR AMBIENTE
[4]PISO''')
print('<'*40)
opcao = int(input('Opção: '))
time.sleep(2)
if opcao == 1:
    print('TIPO DE CÁLCULO: [1]ÁREA TOTAL')
    print('DIMENSÃO TOTAL DA ÁREA:')
    area_total = float(input('Área total (m²): '))
    time.sleep(2)
    print('>'*40)
    print('DIMENSÕES DO REVESTIMENTO:')
    altura_revestimento = float(input('Altura do revestimento (cm):'))
    largura_revestimento = float(input('Largura do revestimento (cm): '))
    time.sleep(2)
    print('<'*40)
    print('CALCULANDO...')
    time.sleep(3)
    revestimento = altura_revestimento * largura_revestimento
    quantidade = (area_total / revestimento) + (area_total / revestimento) * 10/100
    print('RESULTADO:')
    print(F'REVESTIMENTO: {altura_revestimento:.2f} X {largura_revestimento:.2f}')
    print(F'Área total do revestimento: {area_total:.2f}')
    print(F'Quantidade necessária: {math.ceil(quantidade)} unidades')
    print('OBS: A quantidade já está com acréssimo de 10%')
    time.sleep(3)
    print('ENCERRANDO...')
    time.sleep(5)
    print('FIM DO PROGRAMA')
    print('<>' * 40)
    print('<>' * 40)
elif opcao == 2:
    print('TIPO DE CÁLCULO: [2] INDIVIDUAL')
    print('DIMENSÃO DA PAREDE:')
    altura_parede = float(input('Altura parede (1)(m): '))
    largura_parede = float(input('Largura parede (1) (m): '))
    time.sleep(2)
    print('>'*40)
    print('DIMENSÕES DO REVESTIMENTO:')
    altura_revestimento = float(input('Altura revestimento (cm): '))
    largura_revestimento = float(input('Largura revestimento (cm): '))
    time.sleep(2)
    print('<'*40)
    print('CALCULANDO...')
    time.sleep(3)
    area_total = altura_parede * largura_parede
    revestimento = altura_revestimento * largura_revestimento
    quantidade = (area_total / revestimento) + (area_total / revestimento) * 10/100
    print('>'*40)
    print('RESULTADO:')
    print(f'Área total: {area_total:.2f}m²')
    print(f'Revestimento: {altura_revestimento}X{largura_revestimento}')
    print(f'Quantidade: {math.ceil(quantidade)} unidades')
    print('OBS: A quantidade já está com acréssimo de 10%')
    time.sleep(3)
    print('ENCERRANDO...')
    time.sleep(5)
    print('FIM DO PROGRAMA')
    print('<>'*40)
    print('<>' * 40)
elif opcao == 3:
    print('TIPO DE CÁLCULO: [3]POR AMBIENTE')
    print('DIMENSÃO DO AMBIENTE:')
    altura_parede_1 = float(input('Altura parede (1) (m): '))
    largura_parede_1 = float(input('Largura parede (1)(m): '))
    altura_parede_2 = float(input('Altura parede (2) (m): '))
    largura_parede_2 = float(input('Largura parede (2) (m): '))
    time.sleep(2)
    print('>'*40)
    print('DESCONTO DE VÃOS - PORTA/JANELA')
    altura_porta = float(input('Altura porta (m): '))
    largura_porta = float(input('Largura porta (cm/m): '))
    altura_janela = float(input('Altura janela (cm/m): '))
    largura_janela = float(input('Largura janela (cm/m): '))
    time.sleep(2)
    print('<'*40)
    print('DIMENSÕES DO REVESTIMENTO:')
    altura_revestimento = float(input('Altura revestimento (cm): '))
    largura_revestimento = float(input('largura revestimento (cm): '))
    time.sleep(2)
    print('>'*40)
    print('CALCULANDO...')
    time.sleep(3)
    desconto = (altura_porta * largura_porta) + (altura_janela * largura_janela)
    area_total = (altura_parede_1 * largura_parede_1 * 2) + (altura_parede_2 * largura_parede_2 * 2) - desconto
    revestimento = altura_revestimento * largura_revestimento
    quantidade = (area_total / revestimento) + (area_total / revestimento)*10/100
    print('<'*40)
    print('RESULTADO:3')
    print(f'Área total: {area_total:.2f}')
    print(f'Revestimento: {altura_revestimento:.2f}X{largura_revestimento:.2f}')
    print(f'Quantidade: {math.ceil(quantidade)} unidades')
    print('OBS: A quantidade já está com acréssimo de 10%')
    time.sleep(3)
    print('ENCERRANDO...')
    time.sleep(5)
    print('FIM DO PROGRAMA')
    print('<>' * 40)
    print('<>' * 40)
elif opcao == 4:
    print('TIPO DE CÁLCULO: [4]PISO')
    print('DIMENSÕES DO PISO:')
    largura_piso = float(input('Largura piso (m): '))
    profundidade_piso = float(input('Profundidade piso (m): '))
    print('>'*40)
    print('DIMENSÕES DO REVESTIMENTO:')
    altura_revestimento = float(input('Altura revestimento: '))
    largura_revestimento = float(input('Largura revestimento: '))
    time.sleep(2)
    print('<'*40)
    print('CALCULANDO...')
    time.sleep(5)
    area_piso = largura_piso * profundidade_piso
    revestimento = altura_revestimento * largura_revestimento
    quantidade = (area_piso / revestimento) + (area_piso / revestimento)*10/100
    print('>'*40)
    print('RESULTADO:')
    print(f'Área do piso: {area_piso:.2f}m²')
    print(f'Revestimento: {altura_revestimento:.2f}X{largura_revestimento:.2f}')
    print(f'Quantidade: {math.ceil(quantidade)} unidades')
    print('OBS: A quantidade já está com acréssimo de 10%')
    time.sleep(3)
    print('ENCERRANDO...')
    time.sleep(5)
    print('FIM DO PROGRAMA')
    print('<>' * 40)
    print('<>' * 40)
else:
    print('OPÇÃO INCORRETA')
    print('ESCOLHA UMA OPÇÃO VÁLIDA')

